[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "arfc-experiments"
version = "0.1.0"
description = "ARFC project experiments"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "av==14.2.0",
    "datasets==3.4.0",
    "fire==0.7.0",
    "ipython",
    "jupyter",
    "matplotlib==3.10.1",
    "neuromaps",
    "nibabel==5.3.2",
    "nilearn==0.11.1",
    "nisc",
    "numpy==1.26.4",
    "pandas==2.2.3",
    "pip>=25.0.1",
    "pre-commit>=4.1.0",
    "pyspi==1.1.1",
    "pytest>=8.3.5",
    "pyvista[jupyter]==0.43.10",
    "rust-just==1.40.0",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "skarf",
    "statsmodels==0.14.4",
    "tqdm>=4.66.0",
    "typer>=0.15.3",
    "yaspy",
]

[tool.uv.sources]
skarf = { path = "submodules/skarf", editable = true }
yaspy = { path = "submodules/yaspy", editable = true }
nisc = { git = "https://github.com/clane9/nisc.git", rev = "667f98814b63fecbb158b7a96b8e6f7dbebb0eb2" }
neuromaps = { git = "https://github.com/netneurolab/neuromaps.git", tag = "0.0.5" }

[tool.uv]
config-settings = { editable_mode = "compat" }

[tool.setuptools_scm]
version_file = "src/arfcexp/_version.py"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
